Fixed up to run on the BeagleBoard

diff --git a/mkxmbootscr b/mkxmbootscr
--- a/mkxmbootscr
+++ b/mkxmbootscr
@@ -1,6 +1,13 @@
-#!/bin/sh
-
+#!/bin/bash
 TMPFILE=/tmp/$(basename $0).$$.cmd
+
+for tool in mkimage; do
+	if ! type $tool >/dev/null 2>&1; then
+		echo "ERROR: \"$tool\" not found."
+		echo "	Try 'opkg install u-boot-mkimage'"
+		exit 2
+	fi
+done
 
 function do_mkimage {
 echo Building script \""$1\"" - $2
@@ -28,6 +35,14 @@ fatload mmc 0 0x82000000 uImage
 bootm 0x82000000
 EOF
 do_mkimage "Default (720p)" boot-hd.scr
+
+cat <<EOF > $TMPFILE
+setenv bootargs 'console=tty0 console=ttyS2,115200n8 mpurate=1000 nohz=off vram=16M omapfb.mode=dvi:640x480MR-16@60 omapdss.def_disp=dvi omapfb.vram=0:8M,1:4M,2:4M root=/dev/ram0 rw rootfstype=ext2 initrd=0x81600000,32M ramdisk_size=32768 mem=99M@0x80000000 mem=384M@0x88000000'
+fatload mmc 0 0x80200000 uImage
+fatload mmc 0 0x81600000 ramdisk.gz
+bootm 0x80200000
+EOF
+do_mkimage "Ramdisk" boot-ram.scr
 
 rm $TMPFILE
 
